"""add_comments_to_issues

Revision ID: 98306834485f
Revises: d39cb996a60d
Create Date: 2025-07-26 14:30:07.869090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98306834485f'
down_revision: Union[str, None] = 'd39cb996a60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'comments')
    # ### end Alembic commands ###
