"""add issue_id column and index to issues table

Revision ID: bb257883e1e3
Revises: 98306834485f
Create Date: 2025-07-26 16:29:26.466433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb257883e1e3'
down_revision: Union[str, None] = '98306834485f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('issue_id', sa.String(), nullable=True))
    op.create_index('ix_issues_issue_id', 'issues', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issues_issue_id', table_name='issues')
    op.drop_column('issues', 'issue_id')
    # ### end Alembic commands ###
