"""Add enhanced reload tracking fields

Revision ID: bf638c72e3b1
Revises: d0df37c26fa3
Create Date: 2025-07-24 20:56:22.860934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf638c72e3b1'
down_revision: Union[str, None] = 'd0df37c26fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reload_tracking', sa.Column('source', sa.String(), nullable=True))
    op.add_column('reload_tracking', sa.Column('triggered_by', sa.String(), nullable=True))
    op.add_column('reload_tracking', sa.Column('issues_deleted', sa.Integer(), nullable=True))
    op.add_column('reload_tracking', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reload_tracking', 'duration_seconds')
    op.drop_column('reload_tracking', 'issues_deleted')
    op.drop_column('reload_tracking', 'triggered_by')
    op.drop_column('reload_tracking', 'source')
    # ### end Alembic commands ###
