"""add blacklist_reason to issues table

Revision ID: d39cb996a60d
Revises: d1c661833f40
Create Date: 2025-07-26 13:32:24.502966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39cb996a60d'
down_revision: Union[str, None] = 'd1c661833f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('blacklist_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'blacklist_reason')
    # ### end Alembic commands ###
